/*
TGJU Web Service

Testing GeneralAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package persianapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sajadsafary/persianapi"
)

func Test_persianapi_GeneralAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GeneralAPIService WebServiceCommonGoldCurrencyCoinGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GeneralAPI.WebServiceCommonGoldCurrencyCoinGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
