/*
TGJU Web Service

TGJU Web Service Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package persianapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AllCommon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllCommon{}

// AllCommon struct for AllCommon
type AllCommon struct {
	Key int32 `json:"key"`
	Category string `json:"category"`
	Title string `json:"title"`
	Price string `json:"price"`
	Change AllCommonChange `json:"change"`
	Low string `json:"low"`
	High string `json:"high"`
	CreatedAt string `json:"created_at"`
}

type _AllCommon AllCommon

// NewAllCommon instantiates a new AllCommon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllCommon(key int32, category string, title string, price string, change AllCommonChange, low string, high string, createdAt string) *AllCommon {
	this := AllCommon{}
	this.Key = key
	this.Category = category
	this.Title = title
	this.Price = price
	this.Change = change
	this.Low = low
	this.High = high
	this.CreatedAt = createdAt
	return &this
}

// NewAllCommonWithDefaults instantiates a new AllCommon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllCommonWithDefaults() *AllCommon {
	this := AllCommon{}
	return &this
}

// GetKey returns the Key field value
func (o *AllCommon) GetKey() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetKeyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *AllCommon) SetKey(v int32) {
	o.Key = v
}

// GetCategory returns the Category field value
func (o *AllCommon) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *AllCommon) SetCategory(v string) {
	o.Category = v
}

// GetTitle returns the Title field value
func (o *AllCommon) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *AllCommon) SetTitle(v string) {
	o.Title = v
}

// GetPrice returns the Price field value
func (o *AllCommon) GetPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *AllCommon) SetPrice(v string) {
	o.Price = v
}

// GetChange returns the Change field value
func (o *AllCommon) GetChange() AllCommonChange {
	if o == nil {
		var ret AllCommonChange
		return ret
	}

	return o.Change
}

// GetChangeOk returns a tuple with the Change field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetChangeOk() (*AllCommonChange, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Change, true
}

// SetChange sets field value
func (o *AllCommon) SetChange(v AllCommonChange) {
	o.Change = v
}

// GetLow returns the Low field value
func (o *AllCommon) GetLow() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Low
}

// GetLowOk returns a tuple with the Low field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetLowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Low, true
}

// SetLow sets field value
func (o *AllCommon) SetLow(v string) {
	o.Low = v
}

// GetHigh returns the High field value
func (o *AllCommon) GetHigh() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.High
}

// GetHighOk returns a tuple with the High field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetHighOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.High, true
}

// SetHigh sets field value
func (o *AllCommon) SetHigh(v string) {
	o.High = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AllCommon) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AllCommon) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AllCommon) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o AllCommon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllCommon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["category"] = o.Category
	toSerialize["title"] = o.Title
	toSerialize["price"] = o.Price
	toSerialize["change"] = o.Change
	toSerialize["low"] = o.Low
	toSerialize["high"] = o.High
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *AllCommon) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"category",
		"title",
		"price",
		"change",
		"low",
		"high",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAllCommon := _AllCommon{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAllCommon)

	if err != nil {
		return err
	}

	*o = AllCommon(varAllCommon)

	return err
}

type NullableAllCommon struct {
	value *AllCommon
	isSet bool
}

func (v NullableAllCommon) Get() *AllCommon {
	return v.value
}

func (v *NullableAllCommon) Set(val *AllCommon) {
	v.value = val
	v.isSet = true
}

func (v NullableAllCommon) IsSet() bool {
	return v.isSet
}

func (v *NullableAllCommon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllCommon(val *AllCommon) *NullableAllCommon {
	return &NullableAllCommon{value: val, isSet: true}
}

func (v NullableAllCommon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllCommon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


