/*
TGJU Web Service

TGJU Web Service Documentation

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package persianapi

import (
	"encoding/json"
)

// checks if the CommonGoldCurrencyCoin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonGoldCurrencyCoin{}

// CommonGoldCurrencyCoin struct for CommonGoldCurrencyCoin
type CommonGoldCurrencyCoin struct {
	Result []AllCommon `json:"result,omitempty"`
}

// NewCommonGoldCurrencyCoin instantiates a new CommonGoldCurrencyCoin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonGoldCurrencyCoin() *CommonGoldCurrencyCoin {
	this := CommonGoldCurrencyCoin{}
	return &this
}

// NewCommonGoldCurrencyCoinWithDefaults instantiates a new CommonGoldCurrencyCoin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonGoldCurrencyCoinWithDefaults() *CommonGoldCurrencyCoin {
	this := CommonGoldCurrencyCoin{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CommonGoldCurrencyCoin) GetResult() []AllCommon {
	if o == nil || IsNil(o.Result) {
		var ret []AllCommon
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonGoldCurrencyCoin) GetResultOk() ([]AllCommon, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CommonGoldCurrencyCoin) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []AllCommon and assigns it to the Result field.
func (o *CommonGoldCurrencyCoin) SetResult(v []AllCommon) {
	o.Result = v
}

func (o CommonGoldCurrencyCoin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonGoldCurrencyCoin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableCommonGoldCurrencyCoin struct {
	value *CommonGoldCurrencyCoin
	isSet bool
}

func (v NullableCommonGoldCurrencyCoin) Get() *CommonGoldCurrencyCoin {
	return v.value
}

func (v *NullableCommonGoldCurrencyCoin) Set(val *CommonGoldCurrencyCoin) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonGoldCurrencyCoin) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonGoldCurrencyCoin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonGoldCurrencyCoin(val *CommonGoldCurrencyCoin) *NullableCommonGoldCurrencyCoin {
	return &NullableCommonGoldCurrencyCoin{value: val, isSet: true}
}

func (v NullableCommonGoldCurrencyCoin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonGoldCurrencyCoin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


